/**
Copyright 2014 Miyuru Dayarathna

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */

package org.streamfarm.query;

/**
 * @author miyuru
 *
 */
public enum QueryResults {
	ERROR, 
	ACCEPT, 
	
	//------------------------------------- SELECT Expressions -------------------------------------------
	
	//--------------------- General Springs and Sinkholes ------------------------------------------------
	
	SELECT_AST_PROT_SPRINGS, //Case 73
	SELECT_N_PROT_SPRINGS, //Case 74
	SELECT_AST_PROT_SINKHOLES, //Case 75
	SELECT_N_PROT_SINKHOLES, //Case 76

	SELECT_DATARATE_FROM_SPRINGS, //Case 77
	SELECT_DATARATE_FROM_SPRINGS_AST_OF_VARNAME, //Case 78
	SELECT_DATARATE_FROM_SPRINGS_AST_ON_HOST, //Case 79
	SELECT_DATARATE_FROM_SPRINGS_AST_OF_VARNAME_ON_HOST, //Case 80
	SELECT_DATARATE_FROM_PROT_SPRINGS_AST_ON_HOST, //Case 81
	SELECT_DATARATE_FROM_PROT_SPRINGS_N_ON_HOST, //Case 82
	
	SELECT_DATARATE_FROM_SINKHOLES, //Case 83
	SELECT_DATARATE_FROM_SINKHOLES_AST_OF_VARNAME, //Case 84
	SELECT_DATARATE_FROM_SINKHOLES_AST_ON_HOST, //Case 85
	SELECT_DATARATE_FROM_SINKHOLES_AST_OF_VARNAME_ON_HOST, //Case 86
	SELECT_DATARATE_FROM_PROT_SINKHOLES_AST_ON_HOST, //Case 87
	SELECT_DATARATE_FROM_PROT_SINKHOLES_N_ON_HOST, //Case 88
	
	SELECT_SUM_DATARATE_FROM_SPRINGS, //Case 89
	SELECT_SUM_DATARATE_FROM_SPRINGS_AST_OF_VARNAME, //Case 90
	SELECT_SUM_DATARATE_FROM_SPRINGS_AST_ON_HOST, //Case 91
	SELECT_SUM_DATARATE_FROM_SPRINGS_AST_OF_VARNAME_ON_HOST, //Case 92
	SELECT_SUM_DATARATE_FROM_PROT_SPRINGS_AST_ON_HOST, //Case 93
	SELECT_SUM_DATARATE_FROM_PROT_SPRINGS_N_ON_HOST, //Case 94
	
	SELECT_SUM_DATARATE_FROM_SINKHOLES, //Case 95
	SELECT_SUM_DATARATE_FROM_SINKHOLES_AST_OF_VARNAME, //Case 96
	SELECT_SUM_DATARATE_FROM_SINKHOLES_AST_ON_HOST, //Case 97
	SELECT_SUM_DATARATE_FROM_SINKHOLES_AST_OF_VARNAME_ON_HOST, //Case 98
	SELECT_SUM_DATARATE_FROM_PROT_SINKHOLES_AST_ON_HOST, //Case 99
	SELECT_SUM_DATARATE_FROM_PROT_SINKHOLES_N_ON_HOST, //Case 100
	
	//--------------------- General PSprings and PSinkholes ------------------------------------------------
	
	SELECT_AST_PROT_PSPRINGS, //Case 101
	SELECT_N_PROTOCOL_PSPRINGS, //Case 102
	SELECT_AST_PROTOCOL_PSINKHOLES, //Case 103
	SELECT_N_PROTOCOL_PSINKHOLES, //Case 104
	SELECT_N_PROT_PSINKHOLES, //Case 104

	SELECT_DATARATE_FROM_PSPRINGS, //Case 105
	SELECT_DATARATE_FROM_PSPRINGS_AST_OF_VARNAME, //Case 106
	SELECT_DATARATE_FROM_PSPRINGS_AST_ON_HOST, //Case 107
	SELECT_DATARATE_FROM_PSPRINGS_AST_OF_VARNAME_ON_HOST, //Case 108
	SELECT_DATARATE_FROM_PROTOCOL_PSPRINGS_AST_ON_HOST, //Case 109
	SELECT_DATARATE_FROM_PROTOCOL_PSPRINGS_N_ON_HOST, //Case 110
	
	SELECT_DATARATE_FROM_PSINKHOLES, //Case 111
	SELECT_DATARATE_FROM_PSINKHOLES_AST_OF_VARNAME, //Case 112
	SELECT_DATARATE_FROM_PSINKHOLES_AST_ON_HOST, //Case 113
	SELECT_DATARATE_FROM_PSINKHOLES_AST_OF_VARNAME_ON_HOST, //Case 114
	SELECT_DATARATE_FROM_PROTOCOL_PSINKHOLES_AST_ON_HOST, //Case 115
	SELECT_DATARATE_FROM_PROTOCOL_PSINKHOLES_N_ON_HOST, //Case 116
	
	SELECT_SUM_DATARATE_FROM_PSPRINGS, //Case 117
	SELECT_SUM_DATARATE_FROM_PSPRINGS_AST_OF_VARNAME, //Case 118
	SELECT_SUM_DATARATE_FROM_PSPRINGS_AST_ON_HOST, //Case 119
	SELECT_SUM_DATARATE_FROM_PSPRINGS_AST_OF_VARNAME_ON_HOST, //Case 120
	SELECT_SUM_DATARATE_FROM_PROTOCOL_PSPRINGS_AST_ON_HOST, //Case 121
	SELECT_SUM_DATARATE_FROM_PROTOCOL_PSPRINGS_N_ON_HOST, //Case 122
	
	SELECT_SUM_DATARATE_FROM_PSINKHOLES, //Case 123
	SELECT_SUM_DATARATE_FROM_PSINKHOLES_AST_OF_VARNAME, //Case 106
	SELECT_SUM_DATARATE_FROM_PSINKHOLES_AST_ON_HOST, //Case 107
	SELECT_SUM_DATARATE_FROM_PSINKHOLES_AST_OF_VARNAME_ON_HOST, //Case 108
	SELECT_SUM_DATARATE_FROM_PROTOCOL_PSINKHOLES_AST_ON_HOST, //Case 109
	SELECT_SUM_DATARATE_FROM_PROTOCOL_PSINKHOLES_N_ON_HOST, //Case 110

	//--------------------- General ESprings ------------------------------------------------
	
	SELECT_AST_PROT_ESPRINGS, //Case 111
	SELECT_N_PROTOCOL_ESPRINGS, //Case 112
	SELECT_AST_PROTOCOL_ESINKHOLES, //Case 113
	SELECT_N_PROT_ESINKHOLES, //Case 114

	SELECT_DATARATE_FROM_ESPRINGS, //Case 115
	SELECT_DATARATE_FROM_ESPRINGS_AST_OF_VARNAME, //Case 116
	SELECT_DATARATE_FROM_ESPRINGS_AST_ON_HOST, //Case 117
	SELECT_DATARATE_FROM_ESPRINGS_AST_OF_VARNAME_ON_HOST, //Case 118
	SELECT_DATARATE_FROM_PROTOCOL_ESPRINGS_AST_ON_HOST, //Case 119
	SELECT_DATARATE_FROM_PROTOCOL_ESPRINGS_N_ON_HOST, //Case 120
	
	SELECT_SUM_DATARATE_FROM_ESPRINGS, //Case 127
	SELECT_SUM_DATARATE_FROM_ESPRINGS_AST_OF_VARNAME, //Case 128
	SELECT_SUM_DATARATE_FROM_ESPRINGS_AST_ON_HOST, //Case 129
	SELECT_SUM_DATARATE_FROM_ESPRINGS_AST_OF_VARNAME_ON_HOST, //Case 130
	SELECT_SUM_DATARATE_FROM_PROTOCOL_ESPRINGS_AST_ON_HOST, //Case 131
	SELECT_SUM_DATARATE_FROM_PROTOCOL_ESPRINGS_N_ON_HOST, //Case 132
	
	//--------------------- General GSprings ------------------------------------------------
	
	SELECT_AST_PROT_GSPRINGS, //Case 133
	SELECT_N_PROTOCOL_GSPRINGS, //Case 134
	SELECT_AST_PROTOCOL_GSINKHOLES, //Case 135
	SELECT_N_PROT_GSINKHOLES, //Case 136

	SELECT_DATARATE_FROM_GSPRINGS, //Case 137
	SELECT_DATARATE_FROM_GSPRINGS_AST_OF_VARNAME, //Case 138
	SELECT_DATARATE_FROM_GSPRINGS_AST_ON_HOST, //Case 139
	SELECT_DATARATE_FROM_GSPRINGS_AST_OF_VARNAME_ON_HOST, //Case 140
	SELECT_DATARATE_FROM_PROTOCOL_GSPRINGS_AST_ON_HOST, //Case 141
	SELECT_DATARATE_FROM_PROTOCOL_GSPRINGS_N_ON_HOST, //Case 142
	
	SELECT_SUM_DATARATE_FROM_GSPRINGS, //Case 149
	SELECT_SUM_DATARATE_FROM_GSPRINGS_AST_OF_VARNAME, //Case 150
	SELECT_SUM_DATARATE_FROM_GSPRINGS_AST_ON_HOST, //Case 151
	SELECT_SUM_DATARATE_FROM_GSPRINGS_AST_OF_VARNAME_ON_HOST, //Case 152
	SELECT_SUM_DATARATE_FROM_PROTOCOL_GSPRINGS_AST_ON_HOST, //Case 153
	SELECT_SUM_DATARATE_FROM_PROTOCOL_GSPRINGS_N_ON_HOST, //Case 154
	
	//------------------------------------- STATSU Expressions -------------------------------------------
	
	LIST_STATUS, //Case 5
	
	//------------------------------------- CREATE Expressions -------------------------------------------
	
	CREATE_N_PROTOCOL_PSPRINGS_FROM_FILE_AS_VARNAME, //Case 1
	CREATE_N_PROTOCOL_PSPRINGS_FROM_FILE_ON_HOST_AS_VARNAME, //Case 2
	CREATE_N_PROTOCOL_PSPRINGS_FROM_FILE_ON_HOST_AS_VARNAME_WITH_MAXDRATE_R, //Case 3
	CREATE_N_PROTOCOL_PSINKHOLES_ON_HOST_AS_VARNAME,//Case 4
	CREATE_N_PROTOCOL_PSINKHOLES_ON_HOST_AS_VARNAME_WITH_MAXDRATE_R,//Case 5
	
	CREATE_FILTER_X_Y_EXPR_AS_VARNAME_WITH_DRANGE_D_IN_PERIOD_P,//Case 6
	CREATE_FILTER_PULSEWAVE_AS_VARNAME_WITH_DRANGE_D_IN_PERIOD_P,//Case 7
	
	CREATE_N_PROTOCOL_KRONECKER_GSPRINGS_USING_MATRIX_MATRIXDEF_NITER_N,//Case 8
	CREATE_N_PROTOCOL_KRONECKER_GSPRINGS_ON_HOST_USING_MATRIX_MATRIXDEF_NITER_N,//Case 9
	CREATE_N_PROTOCOL_KRONECKER_GSPRINGS_ON_HOST_AS_VARNAME_USING_MATRIX_MATRIXDEF_NITER_N,//Case 10
	CREATE_N_PROTOCOL_KRONECKER_GSPRINGS_ON_HOST_AS_VARNAME_WITH_MAXDRATE_D_USING_MATRIX_MATRIXDEF_NITER_N,//Case 11
	
	CREATE_N_PROTOCOL_ESPRINGS_FROM_URLPATH_AS_VARNAME,//CASE12
	CREATE_N_PROTOCOL_ESPRINGS_FROM_URLPATH_ON_HOST_AS_VARNAME,//CASE13
	CREATE_N_PROTOCOL_ESPRINGS_FROM_URLPATH_ON_HOST_AS_VARNAME_WITH_MAXDRATE_D_LEARN_FOR_T,//CASE14
	CREATE_N_PROTOCOL_ESPRINGS_FROM_URLPATH_ON_HOST_AS_VARNAME_WITH_MAXDRATE_D_LEARN_FOR_T_SAVE,//CASE15
	CREATE_N_PROTOCOL_ESPRINGS_FROM_URLPATH_ON_HOST,//CASE16
	CREATE_N_PROTOCOL_ESPRINGS_FROM_URLPATH_ON_HOST_WITH_MAXDRATE_DLEARN_FOR_T,//CASE17
	CREATE_N_PROTOCOL_ESPRINGS_FROM_URLPATH_ON_HOST_WITH_MAXDRATE_D_LEARN_FOR_T_SAVE,//CASE18
	
	CREATE_N_PROTOCOL_ASPRINGS_FROM_URLPATH_AS_VARNAME_WITH_MAXDRATE_D_AMPLIFYING_URLPATH, //Case 19
	CREATE_N_PROTOCOL_ASPRINGS_FROM_URLPATH_ON_HOST_AS_VARNAME_WITH_MAXDRATE_D_AMPLIFYING_URLPATH,//Case 20
	
	//------------------------------------- SET Expressions ---------------------------------------------
	SET_FILTERS_VARNAME_ON_PROTOCOLS_PSPRINGS_P_ON_HOST,//CASE21
	SET_FILTERS_VARNAME_ON_PROTOCOLS_PSPRINGS_P_ON_HOST_NRPT_N,//CASE22
	
	//------------------------------------- REMOVE Expressions ------------------------------------------
	REMOVE_FILTERS_AST_ON_PROTOCOL_PSPRINGS_N_ON_HOST, //CASE23
	REMOVE_FILTERS_AST_ON_PSPRINGS_AST_ON_HOST, //CASE24
	REMOVE_FILTERS_AST_ON_PSPRINGS_AST_ON_HOST_OF_VARNAME,//CASE25
	REMOVE_FILTERS_VARNAME_ON_PSPRINGS_AST_ON_HOST_OF_VARNAME, //CASE26
	REMOVE_FILTERS_AST_ON_PSPRINGS_AST_OF_VARNAME,//CASE27
	REMOVE_FILTERS_VARNAME_ON_PSPRINGS_AST_ON_HOST,//CASE28
	REMOVE_FILTERS_VARNAME_ON_PSPRINGS_N_ON_HOST,//CASE29
	REMOVE_FILTERS_AST_ON_PSPRINGS_N_ON_HOST,//CASE30
	REMOVE_FILTERS_VARNAME_ON_PROTOCOL_PSPRINGS_N_ON_HOST,//CASE31
	
	//------------------------------------ DELETE Expressions -------------------------------------------
	
	DELETE_PSPRINGS_AST_OF_VARNAME, //Case 32
	DELETE_PSPRINGS_AST_ON_HOST, //Case 33
	DELETE_PROTOCOL_PSPRINGS_AST_ON_HOST, //Case 34
	DELETE_PROTCOL_PSPRINGS_AST_ON_HOST_OF_VARNAME, //Case 35
	DELETE_PSPRINGS_AST_ON_HOST_OF_VARNAME,//Case 36
	DELETE_PROTCOL_PSPRINGS_N_ON_HOST, //Case 37
	
	DELETE_ESPRINGS_AST_ON_HOST, //Case 38
	DELETE_PROTOCOL_ESPRINGS_AST_ON_HOST, //Case 39
	DELETE_PROTCOL_ESPRINGS_AST_ON_HOST, //Case 40
	DELETE_PROTCOL_ESPRINGS_AST_ON_HOST_OF_VARNAME, //Case 41
	DELETE_ESPRINGS_AST_ON_HOST_OF_VARNAME,//Case 42
	DELETE_PROTCOL_ESPRINGS_N_ON_HOST, //Case 43
	
	DELETE_ASPRINGS_AST_ON_VARNAME, //Case 44
	DELETE_ASPRINGS_AST_ON_HOST, //Case 45
	DELETE_PROTCOL_ASPRINGS_AST_ON_HOST,//Case 46
	DELETE_PROTOCOL_ASPRINGS_AST_ON_HOST, //Case 46
	DELETE_PROTCOL_ASPRINGS_AST_ON_HOST_OF_VARNAME, //Case 47
	DELETE_ASPRINGS_AST_ON_HOST_OF_VARNAME,//Case 48
	DELETE_PROTOCOL_ASPRINGS_N_ON_HOST,//Case 49
	
	DELETE_GSPRINGS_AST_ON_VARNAME, //Case 50
	DELETE_GSPRINGS_AST_ON_HOST, //Case 51
	DELETE_PROTOCOL_GSPRINGS_AST_ON_HOST, //Case 52
	DELETE_PROTCOL_GSPRINGS_AST_ON_HOST_OF_VARNAME, //Case 53
	DELETE_GSPRINGS_AST_ON_HOST_OF_VARNAME,//Case 54
	DELETE_PROTCOL_GSPRINGS_N_ON_HOST, //Case 55
	
	DELETE_SPRINGS_AST_OF_VARNAME,//CASE 56
	DELETE_SPRINGS_AST_ON_HOST,//CASE 57
	DELETE_PROTOCOL_SPRINGS_AST_ON_HOST,//CASE 58
	
	DELETE_SINKHOLES_AST_OF_VARNAME, //Case 59
	DELETE_SINKHOLES_AST_ON_HOST, //Case 60
	DELETE_PROT_SINKHOLES_AST_ON_HOST, //Case 61
	
	DELETE_PSINKHOLES_AST_OF_VARNAME,//Case 62
	DELETE_PSINKHOLES_AST_ON_HOST, //CASE 63
	DELETE_PROTOCOL_PSINKHOLES_AST_ON_HOST, //CASE 64
	DELETE_PROTOCOL_PSINKHOLES_N_ON_HOST, //CASE 65
	
	DELETE_FILTERS_AST,//CASE 66
	DELETE_FILTERS_VARNAME,//CASE 67
	DELETE_FILTERS_VARNAME_ON_HOST,//CASE 68
	DELETE_FILTERS_AST_ON_HOST, //CASE 69
	DELETE_FILTERS_AST_ON_HOST_OF_VARNAME, //CASE 70
	DELETE_FILTERS_AST_OF_VARNAME,//CASE 71
	DELETE_FILTERS_VARNAME_OF_VARNAME,//CASE 72
}
